### ISSUE TITLE
[BUG] Stuck on Singleplayer

### ISSUE THREAD

**Issue by Toxicom** [blaxxun-boop/Resurrection#1] opened 2022-07-15 08:08 UTC
# Description
Dying in a singleplayer world and clicking respawn doesn't actually remove the respawn modal and there is no way to disable it, other than ALT-F4

# Notes
Haven't actually tested with *just* the Resurrection mod. Encountered this bug on two separate modpacks:
- [Raistlin Mage Tower](https://valheim.thunderstore.io/package/RaistlinMageTower/RaistlinMageTower/)
- [Deadheim](https://valheim.thunderstore.io/package/wernermayer/Deadheim/)

# How to reproduce
- [ ] Play singleplayer
- [ ] Get killed
- [ ] Click **Respawn**
- [ ] The Respawn modal is still stuck on the screen with no way to remove

**Comment by IrcDirk** [comment] 2022-07-20 10:22
Same here, but i made workaround (not actual fix) for this => https://github.com/IrcDirk/Resurrection. U need to compile it your self or write me ill send u the updated DLL.

**Comment by Toxicom** [comment] 2022-07-21 06:21
> Same here, but i made workaround (not actual fix) for this => https://github.com/IrcDirk/Resurrection. U need to compile it your self or write me ill send u the updated DLL.

Nah it's fine, I don't need the mod at all and not using it.

**Comment by BraniyaKz** [comment] 2022-07-29 16:17
I can confirm, just experienced this earlier. The log throws an error every time you click the respawn button.

**Comment by blaxxun-boop** [comment] 2022-07-29 16:25
And what's the error?
I am not getting any error here, so sounds like a mod conflict.

**Comment by IrcDirk** [comment] 2022-07-29 16:27
Seems it conflicts with your other mod Groups ;) Ill post the error in a sec...

**Comment by blaxxun-boop** [comment] 2022-07-29 16:28
I obviously have Groups installed as well, and I am still not getting any errors.
Can you please just paste the error here?

**Comment by IrcDirk** [comment] 2022-07-29 16:29
U sure u are checking on Singleplayer? ;) @blaxxun-boop

**Comment by IrcDirk** [comment] 2022-07-29 16:32
> [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
> Stack trace:
> Resurrection.Resurrection.onRespawnClicked () (at <9e14deaf26dd4ae09ca540f7f0b5bf59>:0)
> UnityEngine.Events.InvokableCall.Invoke () (at <c9fb31c2eee14ce4aeb36e4c61e154d8>:0)
> UnityEngine.Events.UnityEvent.Invoke () (at <c9fb31c2eee14ce4aeb36e4c61e154d8>:0)
> UnityEngine.UI.Button.Press () (at <67859b8eac9e4f3b99606821e32b26c6>:0)
> UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <67859b8eac9e4f3b99606821e32b26c6>:0)
> UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <67859b8eac9e4f3b99606821e32b26c6>:0)
> UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <67859b8eac9e4f3b99606821e32b26c6>:0)
> UnityEngine.EventSystems.EventSystem:Update()

**Comment by IrcDirk** [comment] 2022-07-29 16:33
Every time u click "respawn" on **SinglePlayer**.

**Comment by blaxxun-boop** [comment] 2022-07-29 16:41
Okay, so we are probably looking for a mod that destroys the ragdoll of the player.

**Comment by IrcDirk** [comment] 2022-07-29 17:23
@blaxxun-boop found another error, just after first spawn when entering world:

> [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
> Stack trace:
> On.di.RPC_RequestLoadedDLLS (System.Int64 sender, ZPackage pkg) (at <39fc633d37d7407ebc9e8cf4313b7553>:0)
> System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <695d1cc93cca45069c528c15c9fdd749>:0)
> Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
> System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <695d1cc93cca45069c528c15c9fdd749>:0)
> System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <695d1cc93cca45069c528c15c9fdd749>:0)
> System.Delegate.DynamicInvokeImpl (System.Object[] args) (at <695d1cc93cca45069c528c15c9fdd749>:0)
> System.MulticastDelegate.DynamicInvokeImpl (System.Object[] args) (at <695d1cc93cca45069c528c15c9fdd749>:0)
> System.Delegate.DynamicInvoke (System.Object[] args) (at <695d1cc93cca45069c528c15c9fdd749>:0)
> RoutedMethod`1[T].Invoke (System.Int64 rpc, ZPackage pkg) (at <94f274a921864d9db4f1d2703c897047>:0)
> ZRoutedRpc.HandleRoutedRPC (ZRoutedRpc+RoutedRPCData data) (at <94f274a921864d9db4f1d2703c897047>:0)
> ZRoutedRpc.InvokeRoutedRPC (System.Int64 targetPeerID, ZDOID targetZDO, System.String methodName, System.Object[] parameters) (at <94f274a921864d9db4f1d2703c897047>:0)
> ZRoutedRpc.InvokeRoutedRPC (System.Int64 targetPeerID, System.String methodName, System.Object[] parameters) (at <94f274a921864d9db4f1d2703c897047>:0)
> (wrapper dynamic-method) C9F.(object,long,string,object[])
> C9F.Dl (System.Object , System.Int64 , System.String , System.Object[] , C9F ) (at <39fc633d37d7407ebc9e8cf4313b7553>:0)
> mA.YN.PlayerSpawned_Postfix () (at <39fc633d37d7407ebc9e8cf4313b7553>:0)
> (wrapper dynamic-method) Game.DMD<Game::_RequestRespawn>(Game)

Maybe thats the problem? But which mod?

**Comment by blaxxun-boop** [comment] 2022-07-29 17:33
That's AntiCheat, which doesn't work in singleplayer.

**Comment by IrcDirk** [comment] 2022-07-30 07:29
Well that should be fixed by @AzumattDev ... but maybe thats the problem, ill check without AntiCheat.

**Comment by IrcDirk** [comment] 2022-07-30 07:35
Yeah... @AzumattDev **AntiCheat** on **Singleplayer** breaks Resurection.

**Comment by AzumattDev** [comment] 2022-07-30 22:01
Sounds like you aren't on the latest version of the Anticheat @IrcDirk . Either way though, why use the anti-cheat in single player?

**Comment by BraniyaKz** [comment] 2022-07-31 07:01
> HOLD UP, I got it. Its probably OdinPlus's version of ServerSync DeathTweaks. Was throwing errors while using it. Will do some testing without it to confirm, etc ill post here with the log outcome

Edit:
Ive done some more testing. It seems the problems/buginess arise when the Respawn button is clicked right away, as opposed to waiting at least 5 seconds after it appears. Tested w/ groups, resurrection, serversync deathtweaks, and Tombstone Lock set to group. It seems to work perfectly more than half the time, with the occasional character being unresponsive after respawn (fixed with a simple relog, so not much of an issue there).

Long story short: Just wait 5-10 seconds before pressing respawn button, otherwise bugginess occurs, I'm guessing when you have more than one mod messing with deaths in general, theres more operations to run and trying to respawn before those operations have run results in several null pointer exceptions and some other errors. Couldn't get the original log, but it's been working relatively nice since I started actually testing it.

Edit Edit: Another couple of mods to look at compat with would probably be EpicMMO (which has its own experience death loss), and for some reason I have a hunch about Detalhes' ItemRequiresSkillLevel, but probably not. Will do some more testing in the future and report my findings.

**Comment by IrcDirk** [comment] 2022-07-31 09:07
> Sounds like you aren't on the latest version of the Anticheat @IrcDirk . Either way though, why use the anti-cheat in single player?

@AzumattDev So we are preparing new server edition and we testing/preparing some things in single then moving it to multi, so adding and removing AntiCheat would be pain in the ass ;) And yes we dont use 2.0.0 right now.

**Comment by AzumattDev** [comment] 2022-08-01 08:07
> > Sounds like you aren't on the latest version of the Anticheat @IrcDirk . Either way though, why use the anti-cheat in single player?
> 
> @AzumattDev So we are preparing new server edition and we testing/preparing some things in single then moving it to multi, so adding and removing AntiCheat would be pain in the ass ;) And yes we dont use 2.0.0 right now.

Not on latest = not an issue for me to fix/look into :)

**Closed as completed** 2022-10-05 14:28 UTC
